version: '3'
services:
  app:
    container_name: timelines
    build: cmd/timelines/.
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack
    command: >
      /bin/ash -c "
      sleep 3;
      ./timelines;
      "

  postgres:
    build:
      context: cmd/timelines/.
      dockerfile: Dockerfile-Postgres
    container_name: pgsql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5433'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:8081"
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  api:
  database_postgres:

networks:
  fullstack:
    driver: bridge