version: '3'
services:
#  app:
#    container_name: timelines
#    build: cmd/timelinesv2/.
#    ports:
#      - 8080:8080
#    restart: on-failure
#    volumes:
#      - api:/Users/zhughe320/Desktop/local-data/app
#    depends_on:
#      - postgres
#    networks:
#      - fullstack
#    command: >
#      /bin/ash -c "
#      sleep 3;
#      ./timelines;
#      "

  postgres:
    build:
      context: cmd/timelinesv2/.
      dockerfile: Dockerfile-Postgres
    container_name: pgsql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5433:5432'
    volumes:
      - database_postgres:/Users/zhughe320/Desktop/local-data/postgresql
    networks:
      - fullstack

volumes:
#  api:
  database_postgres:

networks:
  fullstack:
    driver: bridge