version: '3'
services:
  app:
    container_name: timelines
    build: cmd/timelines/.
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack
    command: >
      /bin/ash -c "
      sleep 3;
      ./timelines;
      "

  postgres:
    build:
      context: cmd/timelines/.
      dockerfile: Dockerfile-Postgres
    container_name: pgsql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5433:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    environment:
      SWAGGER_JSON: /swagger.json
    ports:
      - "8081:8080"
    volumes:
      - ./cmd/timelines/gen/swagger/timelines.swagger.json:/swagger.json
    networks:
      - fullstack

volumes:
  api:
  database_postgres:

networks:
  fullstack:
    driver: bridge